shared_buffers = 8GB
work_mem = 64MB
synchronous_commit = on
fsync = on
max_connections = 100
log_statement = none
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = all
unix_socket_directories = '/tmp/pgsocket'
port = 5433
